all:
	make -C adb
	make -C libadb
	make -C libcutils
	make -C libzipfile
	make -C zlib

clean:
	make -C adb clean
	make -C libadb clean
	make -C libcutils clean
	make -C libzipfile clean
	make -C zlib clean
